from flask import Flask, render_template, request, send_file
import pickle
import numpy as np
import warnings
from fpdf import FPDF

warnings.filterwarnings("ignore")

app = Flask(__name__)

# load model
with open("disaster_model.pkl","rb") as f:
    model = pickle.load(f)

print("Model loaded successfully")


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/dashboard")
def dashboard():
    return render_template("dashboard.html")


@app.route("/prediction", methods=["GET","POST"])
def prediction():

    result = None
    risk = None

    if request.method == "POST":

        population = float(request.form["population"])
        district = float(request.form["district"])
        disaster_type = float(request.form["disaster_type"])
        rainfall = float(request.form["rainfall"])
        damage = float(request.form["damage"])

        features = np.array([[population, district, disaster_type, rainfall, damage]])

        pred = model.predict(features)[0]

        result = {
            "shelters": int(pred[0]),
            "food": int(pred[1]),
            "rescue": int(pred[2]),
            "deaths": int(pred[3])
        }

        # 🚨 Risk Level Logic

        total_resources = result["shelters"] + result["food"] + result["rescue"]

        if total_resources > 150:
            risk = "High"

        elif total_resources > 80:
            risk = "Medium"

        else:
            risk = "Low"

    return render_template("prediction.html", prediction=result, risk=risk)


# 🚀 PDF REPORT ROUTE

@app.route("/download_report")
def download_report():

    pdf = FPDF()

    pdf.add_page()

    pdf.set_font("Arial", size=16)

    pdf.cell(200,10,txt="AI Disaster Prediction Report",ln=True,align='C')

    pdf.ln(10)

    pdf.set_font("Arial", size=12)

    pdf.cell(200,10,txt="Generated by AI Disaster Resource System",ln=True)

    pdf.ln(5)

    pdf.cell(200,10,txt="Shelters Needed : 40",ln=True)

    pdf.cell(200,10,txt="Food Packets : 500",ln=True)

    pdf.cell(200,10,txt="Rescue Teams : 12",ln=True)

    pdf.cell(200,10,txt="Estimated Casualties : 3",ln=True)

    file_name = "disaster_report.pdf"

    pdf.output(file_name)

    return send_file(file_name, as_attachment=True)


@app.route("/simulation")
def simulation():
    return render_template("simulation.html")


@app.route("/about")
def about():
    return render_template("about.html")


print("Starting Flask server...")

app.run(debug=True)